const API="/api";const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
const signedInUser=JSON.parse(localStorage.getItem('smartfarm-user')||'null');
if(!signedInUser)window.location.replace('login.html');
const fields=[['North Field','Tomatoes · 8.5 acres','🍅','#faeee8',36,'Needs water','watch'],['South Field','Bell peppers · 6 acres','🫑','#e8f2e4',58,'Healthy',''],['West Field','Leafy greens · 4 acres','🥬','#e3f2e5',49,'Healthy',''],['Rice Paddies','Rice · 18 acres','🌾','#fff4dc',68,'On track','']];
let tasks=JSON.parse(localStorage.getItem('smartfarm-tasks'))||[{name:'Inspect North Field irrigation',field:'North Field',date:'Today',done:false},{name:'Apply organic fertilizer',field:'South Field',date:'Today',done:false},{name:'Review pest trap results',field:'West Field',date:'Tomorrow',done:false},{name:'Calibrate soil sensor',field:'Rice Paddies',date:'Friday',done:true}];
let forecast=[];let insights=[];
const weatherIcon=code=>code===0?'☀':code<=3?'⛅':code>=95?'⛈':code>=61?'🌧':'☁';
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function renderFields(){const row=f=>`<div class="fieldrow"><div class="fieldicon" style="background:${f[3]}">${f[2]}</div><div class="fieldname"><b>${f[0]}</b><span>${f[1]}</span></div><div class="moisture"><b>${f[4]}% moisture</b><div class="bar"><i style="width:${f[4]}%"></i></div></div><span class="pill ${f[6]}">${f[5]}</span></div>`;$('#fieldRows').innerHTML=fields.map(row).join('');$('#fieldCards').innerHTML=fields.map(f=>`<article class="fieldcard"><div class="fieldicon" style="background:${f[3]}">${f[2]}</div><span class="pill ${f[6]}">${f[5]}</span><h2>${f[0]}</h2><p>${f[1]}</p><div class="bar"><i style="width:${f[4]}%"></i></div><div class="fielddetail"><span>Soil moisture <b>${f[4]}%</b></span><span>Updated <b>Today</b></span></div></article>`).join('')}
function saveTasks(){localStorage.setItem('smartfarm-tasks',JSON.stringify(tasks))}function renderTasks(){const short=tasks.slice(0,3).map((t,i)=>`<div class="taskrow ${t.done?'done':''}"><button class="check" data-task="${i}">${t.done?'✓':''}</button><p><b>${t.name}</b><small>${t.field}</small></p><span>${t.date}</span></div>`).join('');$('#taskRows').innerHTML=short;$('#allTasks').innerHTML=tasks.map((t,i)=>`<div class="alltask ${t.done?'done':''}"><button class="check" data-task="${i}">${t.done?'✓':''}</button><p><b>${t.name}</b><br><small>${t.field} · Due ${t.date}</small></p><span class="pill ${t.done?'':'watch'}">${t.done?'Complete':'Open'}</span></div>`).join('');$$('.check').forEach(b=>b.onclick=()=>{tasks[b.dataset.task].done=!tasks[b.dataset.task].done;saveTasks();renderTasks();toast(tasks[b.dataset.task].done?'Task marked complete':'Task reopened')})}
function renderForecast(){if(!forecast.length)return;$('#forecastRows').innerHTML=forecast.map((d,i)=>`<div class="forecastrow"><b>${i?'Day '+(i+1):'Today'}</b><span>${weatherIcon(d.weatherCode)}</span><small>${Math.round(d.temperature)}° / ${Math.round(d.temperatureMin)}°</small><div class="bar"><i style="width:${d.precipitationProbability||0}%"></i></div></div>`).join('')}
function renderInsights(){const icon=x=>x.level==='high'?'!':x.level==='medium'?'⌁':'✓';const show=insights.length?insights:[{title:'Fungal disease risk is elevated',level:'medium',text:'Humidity above 75% may affect tomatoes in North Field.',action:'View prevention plan'},{title:'Water use can be optimized',level:'low',text:'Expected rain may reduce irrigation demand this week.',action:'See water schedule'}];$('#shortInsights').innerHTML=show.slice(0,3).map(x=>`<div class="insight ${x.level}"><i>${icon(x)}</i><div><b>${x.title}</b><p>${x.text}</p><button>${x.action} →</button></div></div>`).join('');$('#allInsights').innerHTML=show.map(x=>`<article class="insightcard ${x.level}"><i>${icon(x)}</i><h2>${x.title}</h2><p>${x.text}</p><button>${x.action} →</button></article>`).join('')}
async function loadWeather(){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),10000);try{const r=await fetch(`${API}/weather?latitude=6.9271&longitude=79.8612&location=Colombo%2C%20Sri%20Lanka`,{signal:controller.signal});if(!r.ok)throw Error();const d=await r.json(),c=d.current;forecast=d.forecast;$('#temperature').textContent=`${Math.round(c.temperature)}°`;$('#bigTemperature').innerHTML=`${Math.round(c.temperature)}° <span>${c.condition}</span>`;$('#condition').textContent=c.condition;$('#feels').textContent=`Feels like ${Math.round(c.feelsLike)}°`;$('#humidity').textContent=$('#forecastHumidity').textContent=`${c.humidity}%`;$('#wind').textContent=$('#forecastWind').textContent=`${Math.round(c.windSpeed)} km/h`;const chance=d.forecast[0].precipitationProbability||0;$('#rain').textContent=$('#forecastRain').textContent=`${chance}%`;$('#weatherIcon').textContent=$('#bigIcon').textContent=weatherIcon(c.weatherCode);$('#location').textContent=d.location.name;$('#weatherCity').textContent=d.location.name.toUpperCase();$('#weatherUpdated').textContent='Updated just now';renderForecast();return c}catch{forecast=[{weatherCode:2,temperature:29,temperatureMin:24,precipitationProbability:25},{weatherCode:61,temperature:28,temperatureMin:23,precipitationProbability:58},{weatherCode:3,temperature:30,temperatureMin:24,precipitationProbability:35}];renderForecast();$('#weatherUpdated').textContent='Live weather unavailable · showing cached conditions'}finally{clearTimeout(timer)}}
async function generate(){const b=$('#generate');b.textContent='Generating…';try{const r=await fetch(`${API}/insights/generate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({latitude:6.9271,longitude:79.8612,crop:'Tomatoes',soilMoisture:36,humidity:76})});if(!r.ok)throw Error();const d=await r.json();insights=d.insights;renderInsights();toast('Fresh AI insights generated from live weather data')}catch{toast('AI service is unavailable; showing your latest insights')}finally{b.textContent='✦ Generate insights'}}
function show(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id===view));$$('[data-view]').forEach(a=>a.classList.toggle('active',a.dataset.view===view));$('#side').classList.remove('open');window.scrollTo(0,0)}$$('[data-view]').forEach(a=>a.onclick=e=>{e.preventDefault();show(a.dataset.view)});$('#menu').onclick=()=>$('#side').classList.toggle('open');
function openModal(){$('#modal').classList.add('show');$('#taskName').focus()}function closeModal(){$('#modal').classList.remove('show')}$('#addTask').onclick=openModal;$$('.taskLaunch').forEach(x=>x.onclick=openModal);$('.close').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};$('#taskDate').value=new Date().toISOString().slice(0,10);$('#form').onsubmit=e=>{e.preventDefault();tasks.unshift({name:$('#taskName').value,field:$('#taskField').value,date:'Today',done:false});saveTasks();renderTasks();closeModal();e.target.reset();toast('Task added to your farm plan')};$('#refresh').onclick=async()=>{await loadWeather();toast('Live farm data refreshed')};$('#seeAi').onclick=()=>show('insights');$('#generate').onclick=generate;$('#plan').onclick=()=>toast('Plans are coming soon');$('#download').onclick=()=>toast('Report download is ready');$('#save').onclick=()=>toast('Farm settings saved');
renderFields();renderTasks();renderInsights();loadWeather();generate();

// Account, farm switching, and task filter controls.
if(signedInUser){const initials=signedInUser.name.split(' ').map(part=>part[0]).join('').slice(0,2).toUpperCase();$('#userName').textContent=signedInUser.name;$('#avatar').textContent=initials;}
$('#farmTrigger').onclick=()=>{$('#farmMenu').classList.toggle('show');$('#profileMenu').classList.remove('show')};
$('#profileTrigger').onclick=()=>{$('#profileMenu').classList.toggle('show');$('#farmMenu').classList.remove('show')};
$$('[data-farm]').forEach(button=>button.onclick=()=>{$('#activeFarm').textContent=button.dataset.farm;$('#farmMenu').classList.remove('show');toast(`${button.dataset.farm} is now active`)});
$('#accountBtn').onclick=()=>{show('settings');$('#profileMenu').classList.remove('show')};
$('#logoutBtn').onclick=()=>{localStorage.removeItem('smartfarm-user');window.location.replace('login.html')};
document.addEventListener('click',event=>{if(!event.target.closest('#farmTrigger')&&!event.target.closest('#farmMenu'))$('#farmMenu').classList.remove('show');if(!event.target.closest('#profileTrigger')&&!event.target.closest('#profileMenu'))$('#profileMenu').classList.remove('show')});
function renderTaskFilter(filter){const visible=tasks.map((task,index)=>({task,index})).filter(({task})=>filter==='complete'?task.done:filter==='today'?!task.done&&task.date==='Today':true);$('#allTasks').innerHTML=visible.length?visible.map(({task,index})=>`<div class="alltask ${task.done?'done':''}"><button class="check" data-filter-task="${index}">${task.done?'✓':''}</button><p><b>${task.name}</b><br><small>${task.field} · Due ${task.date}</small></p><span class="pill ${task.done?'':'watch'}">${task.done?'Complete':'Open'}</span></div>`).join(''):'<p class="empty">No tasks in this view.</p>';$$('[data-filter-task]').forEach(button=>button.onclick=()=>{tasks[button.dataset.filterTask].done=!tasks[button.dataset.filterTask].done;saveTasks();renderTasks();renderTaskFilter(filter)})}
$$('[data-filter]').forEach(button=>button.onclick=()=>{$$('[data-filter]').forEach(item=>item.classList.remove('selected'));button.classList.add('selected');renderTaskFilter(button.dataset.filter)});
renderTaskFilter('today');
