const farmSelect = document.getElementById("farmSelect");
const periodSelect = document.getElementById("periodSelect");
const exportButton = document.getElementById("exportButton");

const farmCount = document.getElementById("farmCount");
const cropCount = document.getElementById("cropCount");


const farmData = {

    all: {
        farms: 3,
        crops: 8
    },

    "green-valley": {
        farms: 1,
        crops: 3
    },

    sunrise: {
        farms: 1,
        crops: 2
    },

    "green-hills": {
        farms: 1,
        crops: 3
    }

};


farmSelect.addEventListener("change", function () {

    const selectedFarm = this.value;

    const data = farmData[selectedFarm];

    farmCount.textContent = data.farms;
    cropCount.textContent = data.crops;

});


periodSelect.addEventListener("change", function () {

    console.log(
        "Selected report period:",
        this.value
    );

});


exportButton.addEventListener("click", function () {

    const reportText = `
SMART FARM REPORT
=================

Report Period:
${periodSelect.options[periodSelect.selectedIndex].text}

Farm:
${farmSelect.options[farmSelect.selectedIndex].text}

SUMMARY
-------
Total Farms: ${farmCount.textContent}
Active Crops: ${cropCount.textContent}
Estimated Harvest: 2.8 T
Farm Efficiency: 84%

CROP PERFORMANCE
----------------
Tomato: 78%
Corn: 64%
Rice: 48%
Carrot: 88%

Generated by SmartFarm
`;

    const blob = new Blob(
        [reportText],
        { type: "text/plain" }
    );

    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");

    link.href = url;
    link.download = "smartfarm-report.txt";

    link.click();

    URL.revokeObjectURL(url);

});